export const leftov_data = [
    {
        id: "1",
        type: "001",
        fee_code: "Code1",
        fee_name: false,
        fee_type: "Fixed",
        fee_number: "123",
        ledger: { name: "USD" }
    },
    {
        id: "2",
        type: "002",
        fee_code: "Code2",
        fee_name: "Fee Name 2",
        fee_type: "Monthly",
        fee_number: "456",
        ledger: { name: "MNT" }
    },
    {
        id: "3",
        type: "003",
        fee_code: "Code3",
        fee_name: "Fee Name 3",
        fee_type: "Fixed",
        fee_number: "789",
        ledger: { name: "EUR" }
    },
    {
        id: "4",
        type: "004",
        fee_code: "Code4",
        fee_name: "Fee Name 4",
        fee_type: "Monthly",
        fee_number: "101",
        ledger: { name: "JPY" }
    },
    {
        id: "5",
        type: "005",
        fee_code: "Code5",
        fee_name: "Fee Name 5",
        fee_type: "Fixed",
        fee_number: "112",
        ledger: { name: "GBP" }
    },
    {
        id: "6",
        type: "006",
        fee_code: "Code6",
        fee_name: "Fee Name 6",
        fee_type: "Monthly",
        fee_number: "131",
        ledger: { name: "AUD" }
    },
    {
        id: "7",
        type: "007",
        fee_code: "Code7",
        fee_name: "Fee Name 7",
        fee_type: "Fixed",
        fee_number: "415",
        ledger: { name: "CAD" }
    },
    {
        id: "8",
        type: "008",
        fee_code: "Code8",
        fee_name: "Fee Name 8",
        fee_type: "Monthly",
        fee_number: "161",
        ledger: { name: "CHF" }
    },
    {
        id: "9",
        type: "009",
        fee_code: "Code9",
        fee_name: "Fee Name 9",
        fee_type: "Fixed",
        fee_number: "718",
        ledger: { name: "CNY" }
    },
    {
        id: "10",
        type: "010",
        fee_code: "Code10",
        fee_name: "Fee Name 10",
        fee_type: "Monthly",
        fee_number: "192",
        ledger: { name: "SEK" }
    },
    {
        id: "11",
        type: "011",
        fee_code: "Code11",
        fee_name: "Fee Name 11",
        fee_type: "Fixed",
        fee_number: "223",
        ledger: { name: "NZD" }
    },
    {
        id: "12",
        type: "012",
        fee_code: "Code12",
        fee_name: "Fee Name 12",
        fee_type: "Monthly",
        fee_number: "242",
        ledger: { name: "MXN" }
    },
    {
        id: "13",
        type: "013",
        fee_code: "Code13",
        fee_name: "Fee Name 13",
        fee_type: "Fixed",
        fee_number: "252",
        ledger: { name: "SGD" }
    },
    {
        id: "14",
        type: "014",
        fee_code: "Code14",
        fee_name: "Fee Name 14",
        fee_type: "Monthly",
        fee_number: "262",
        ledger: { name: "HKD" }
    },
    {
        id: "15",
        type: "015",
        fee_code: "Code15",
        fee_name: "Fee Name 15",
        fee_type: "Fixed",
        fee_number: "272",
        ledger: { name: "NOK" }
    },
    {
        id: "16",
        type: "016",
        fee_code: "Code16",
        fee_name: "Fee Name 16",
        fee_type: "Monthly",
        fee_number: "282",
        ledger: { name: "KRW" }
    },
    {
        id: "17",
        type: "017",
        fee_code: "Code17",
        fee_name: "Fee Name 17",
        fee_type: "Fixed",
        fee_number: "292",
        ledger: { name: "TRY" }
    },
    {
        id: "18",
        type: "018",
        fee_code: "Code18",
        fee_name: "Fee Name 18",
        fee_type: "Monthly",
        fee_number: "303",
        ledger: { name: "INR" }
    },
    {
        id: "19",
        type: "019",
        fee_code: "Code19",
        fee_name: "Fee Name 19",
        fee_type: "Fixed",
        fee_number: "313",
        ledger: { name: "BRL" }
    },
    {
        id: "20",
        type: "020",
        fee_code: "Code20",
        fee_name: "Fee Name 20",
        fee_type: "Monthly",
        fee_number: "323",
        ledger: { name: "ZAR" }
    },
    {
        id: "21",
        type: "021",
        fee_code: "Code21",
        fee_name: "Fee Name 21",
        fee_type: "Fixed",
        fee_number: "333",
        ledger: { name: "RUB" }
    },
    {
        id: "22",
        type: "022",
        fee_code: "Code22",
        fee_name: "Fee Name 22",
        fee_type: "Monthly",
        fee_number: "343",
        ledger: { name: "PLN" }
    },
    {
        id: "23",
        type: "023",
        fee_code: "Code23",
        fee_name: "Fee Name 23",
        fee_type: "Fixed",
        fee_number: "353",
        ledger: { name: "DKK" }
    },
    {
        id: "24",
        type: "024",
        fee_code: "Code24",
        fee_name: "Fee Name 24",
        fee_type: "Monthly",
        fee_number: "363",
        ledger: { name: "HUF" }
    },
    {
        id: "25",
        type: "025",
        fee_code: "Code25",
        fee_name: "Fee Name 25",
        fee_type: "Fixed",
        fee_number: "373",
        ledger: { name: "CZK" }
    }
];

export const refinfo_customercompany_data = [
    {
        id: "1",
        type: "001",
        fee_code: "A123",
        fee_name: "Tax",
        fee_type: "Percentage",
        fee_number: "5",
        ledger: { name: "USD" },
    },
    {
        id: "2",
        type: "002",
        fee_code: "B456",
        fee_name: "Service Charge",
        fee_type: "Fixed",
        fee_number: "1000",
        ledger: { name: "MNT" },
    },
    {
        id: "3",
        type: "003",
        fee_code: "C789",
        fee_name: "Handling Fee",
        fee_type: "Fixed",
        fee_number: "500",
        ledger: { name: "USD" },
    },
    {
        id: "4",
        type: "004",
        fee_code: "D101",
        fee_name: "Subscription Fee",
        fee_type: "Monthly",
        fee_number: "2000",
        ledger: { name: "MNT" },
    },
    {
        id: "5",
        type: "005",
        fee_code: "E345",
        fee_name: "Late Fee",
        fee_type: "Percentage",
        fee_number: "10",
        ledger: { name: "USD" },
    },
    {
        id: "6",
        type: "006",
        fee_code: "F678",
        fee_name: "Processing Fee",
        fee_type: "Fixed",
        fee_number: "300",
        ledger: { name: "EUR" },
    },
    {
        id: "7",
        type: "007",
        fee_code: "G910",
        fee_name: "Annual Fee",
        fee_type: "Yearly",
        fee_number: "1500",
        ledger: { name: "JPY" },
    },
    {
        id: "8",
        type: "008",
        fee_code: "H112",
        fee_name: "Maintenance Fee",
        fee_type: "Monthly",
        fee_number: "2500",
        ledger: { name: "GBP" },
    },
    {
        id: "9",
        type: "009",
        fee_code: "I314",
        fee_name: "Transaction Fee",
        fee_type: "Percentage",
        fee_number: "2",
        ledger: { name: "AUD" },
    },
    {
        id: "10",
        type: "010",
        fee_code: "J516",
        fee_name: "Penalty Fee",
        fee_type: "Fixed",
        fee_number: "700",
        ledger: { name: "CAD" },
    },
    {
        id: "11",
        type: "011",
        fee_code: "K718",
        fee_name: "Convenience Fee",
        fee_type: "Fixed",
        fee_number: "400",
        ledger: { name: "CHF" },
    },
    {
        id: "12",
        type: "012",
        fee_code: "L920",
        fee_name: "Overdraft Fee",
        fee_type: "Fixed",
        fee_number: "600",
        ledger: { name: "CNY" },
    },
    {
        id: "13",
        type: "013",
        fee_code: "M122",
        fee_name: "Withdrawal Fee",
        fee_type: "Fixed",
        fee_number: "800",
        ledger: { name: "SEK" },
    },
    {
        id: "14",
        type: "014",
        fee_code: "N324",
        fee_name: "Deposit Fee",
        fee_type: "Fixed",
        fee_number: "900",
        ledger: { name: "NZD" },
    },
    {
        id: "15",
        type: "015",
        fee_code: "O526",
        fee_name: "Transfer Fee",
        fee_type: "Fixed",
        fee_number: "100",
        ledger: { name: "MXN" },
    },
    {
        id: "16",
        type: "016",
        fee_code: "P728",
        fee_name: "Exchange Fee",
        fee_type: "Percentage",
        fee_number: "3",
        ledger: { name: "SGD" },
    },
    {
        id: "17",
        type: "017",
        fee_code: "Q930",
        fee_name: "Conversion Fee",
        fee_type: "Fixed",
        fee_number: "200",
        ledger: { name: "HKD" },
    },
    {
        id: "18",
        type: "018",
        fee_code: "R132",
        fee_name: "Setup Fee",
        fee_type: "Fixed",
        fee_number: "1200",
        ledger: { name: "NOK" },
    },
    {
        id: "19",
        type: "019",
        fee_code: "S334",
        fee_name: "Activation Fee",
        fee_type: "Fixed",
        fee_number: "1300",
        ledger: { name: "KRW" },
    },
    {
        id: "20",
        type: "020",
        fee_code: "T536",
        fee_name: "Deactivation Fee",
        fee_type: "Fixed",
        fee_number: "1400",
        ledger: { name: "TRY" },
    },
    {
        id: "21",
        type: "021",
        fee_code: "U738",
        fee_name: "Reactivation Fee",
        fee_type: "Fixed",
        fee_number: "1500",
        ledger: { name: "INR" },
    },
    {
        id: "22",
        type: "022",
        fee_code: "V940",
        fee_name: "Cancellation Fee",
        fee_type: "Fixed",
        fee_number: "1600",
        ledger: { name: "BRL" },
    },
    {
        id: "23",
        type: "023",
        fee_code: "W142",
        fee_name: "Renewal Fee",
        fee_type: "Yearly",
        fee_number: "1700",
        ledger: { name: "ZAR" },
    },
    {
        id: "24",
        type: "024",
        fee_code: "X344",
        fee_name: "Upgrade Fee",
        fee_type: "Fixed",
        fee_number: "1800",
        ledger: { name: "RUB" },
    },
    {
        id: "25",
        type: "025",
        fee_code: "Y546",
        fee_name: "Downgrade Fee",
        fee_type: "Fixed",
        fee_number: "1900",
        ledger: { name: "PLN" },
    }
]

export const refinfo_additionalfeeset_data = [
    {
        id: "1",
        type: "001",
        fee_code: "A123",
        fee_name: false,
        fee_type: "Fixed",
        fee_number: "500",
        ledger: { name: "USD" },
    },
    {
        id: "2",
        type: "002",
        fee_code: "B456",
        fee_name: "Subscription Fee",
        fee_type: "Monthly",
        fee_number: "1000",
        ledger: { name: "MNT" },
    },
    {
        id: "3",
        type: "003",
        fee_code: "C789",
        fee_name: false,
        fee_type: "Percentage",
        fee_number: "5",
        ledger: { name: "USD" },
    },
    {
        id: "4",
        type: "004",
        fee_code: "D012",
        fee_name: "Processing Fee",
        fee_type: "Fixed",
        fee_number: "300",
        ledger: { name: "MNT" },
    },
    {
        id: "5",
        type: "005",
        fee_code: "E345",
        fee_name: false,
        fee_type: "Percentage",
        fee_number: "10",
        ledger: { name: "USD" },
    },
    {
        id: "6",
        type: "006",
        fee_code: "F678",
        fee_name: "Service Charge",
        fee_type: "Fixed",
        fee_number: "200",
        ledger: { name: "EUR" },
    },
    {
        id: "7",
        type: "007",
        fee_code: "G910",
        fee_name: "Annual Fee",
        fee_type: "Yearly",
        fee_number: "1500",
        ledger: { name: "JPY" },
    },
    {
        id: "8",
        type: "008",
        fee_code: "H112",
        fee_name: "Maintenance Fee",
        fee_type: "Monthly",
        fee_number: "2500",
        ledger: { name: "GBP" },
    },
    {
        id: "9",
        type: "009",
        fee_code: "I314",
        fee_name: "Transaction Fee",
        fee_type: "Percentage",
        fee_number: "2",
        ledger: { name: "AUD" },
    },
    {
        id: "10",
        type: "010",
        fee_code: "J516",
        fee_name: "Penalty Fee",
        fee_type: "Fixed",
        fee_number: "700",
        ledger: { name: "CAD" },
    },
    {
        id: "11",
        type: "011",
        fee_code: "K718",
        fee_name: "Convenience Fee",
        fee_type: "Fixed",
        fee_number: "400",
        ledger: { name: "CHF" },
    },
    {
        id: "12",
        type: "012",
        fee_code: "L920",
        fee_name: "Overdraft Fee",
        fee_type: "Fixed",
        fee_number: "600",
        ledger: { name: "CNY" },
    },
    {
        id: "13",
        type: "013",
        fee_code: "M122",
        fee_name: "Withdrawal Fee",
        fee_type: "Fixed",
        fee_number: "800",
        ledger: { name: "SEK" },
    },
    {
        id: "14",
        type: "014",
        fee_code: "N324",
        fee_name: "Deposit Fee",
        fee_type: "Fixed",
        fee_number: "900",
        ledger: { name: "NZD" },
    },
    {
        id: "15",
        type: "015",
        fee_code: "O526",
        fee_name: "Transfer Fee",
        fee_type: "Fixed",
        fee_number: "100",
        ledger: { name: "MXN" },
    },
    {
        id: "16",
        type: "016",
        fee_code: "P728",
        fee_name: "Exchange Fee",
        fee_type: "Percentage",
        fee_number: "3",
        ledger: { name: "SGD" },
    },
    {
        id: "17",
        type: "017",
        fee_code: "Q930",
        fee_name: "Conversion Fee",
        fee_type: "Fixed",
        fee_number: "200",
        ledger: { name: "HKD" },
    },
    {
        id: "18",
        type: "018",
        fee_code: "R132",
        fee_name: "Setup Fee",
        fee_type: "Fixed",
        fee_number: "1200",
        ledger: { name: "NOK" },
    },
    {
        id: "19",
        type: "019",
        fee_code: "S334",
        fee_name: "Activation Fee",
        fee_type: "Fixed",
        fee_number: "1300",
        ledger: { name: "KRW" },
    },
    {
        id: "20",
        type: "020",
        fee_code: "T536",
        fee_name: "Deactivation Fee",
        fee_type: "Fixed",
        fee_number: "1400",
        ledger: { name: "TRY" },
    },
    {
        id: "21",
        type: "021",
        fee_code: "U738",
        fee_name: "Reactivation Fee",
        fee_type: "Fixed",
        fee_number: "1500",
        ledger: { name: "INR" },
    },
    {
        id: "22",
        type: "022",
        fee_code: "V940",
        fee_name: "Cancellation Fee",
        fee_type: "Fixed",
        fee_number: "1600",
        ledger: { name: "BRL" },
    },
    {
        id: "23",
        type: "023",
        fee_code: "W142",
        fee_name: "Renewal Fee",
        fee_type: "Yearly",
        fee_number: "1700",
        ledger: { name: "ZAR" },
    },
    {
        id: "24",
        type: "024",
        fee_code: "X344",
        fee_name: "Upgrade Fee",
        fee_type: "Fixed",
        fee_number: "1800",
        ledger: { name: "RUB" },
    },
    {
        id: "25",
        type: "025",
        fee_code: "Y546",
        fee_name: "Downgrade Fee",
        fee_type: "Fixed",
        fee_number: "1900",
        ledger: { name: "PLN" },
    }
]